import { useMemo, useState } from 'react';
import { Download, Search, Server } from 'lucide-react';
import { proxiesFromOrders, proxyStatus } from '../../utils/proxyOrders';

export default function ProxyManagementAdmin({ orders = [] }) {
  const [search, setSearch] = useState('');
  const proxies = useMemo(() => proxiesFromOrders(orders), [orders]);
  const visible = proxies.filter(p => `${p.host} ${p.country} ${p.buyerEmail} ${p.orderId}`.toLowerCase().includes(search.toLowerCase()));
  const exportCsv = () => {
    const rows = [['IP', 'Port', 'Client', 'Pays', 'Protocole', 'Expiration', 'Statut', 'Prix', 'Cout'], ...visible.map(p => [p.host, p.port, p.buyerEmail, p.country, p.type, p.expire_time ? new Date(Number(p.expire_time) * 1000).toISOString() : '', proxyStatus(p), p.salePrice, p.supplierCost])];
    const blob = new Blob([rows.map(row => row.map(value => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv' });
    const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'proxies-vendus.csv'; link.click(); URL.revokeObjectURL(url);
  };
  return <div className="space-y-6 animate-in fade-in"><div className="flex items-end justify-between gap-4"><div><div className="text-primary text-xs font-black uppercase tracking-widest flex items-center gap-2"><Server size={15} /> IPFoxy</div><h1 className="text-3xl font-black text-gray-900 dark:text-white mt-2">Gestion des proxies</h1><p className="text-sm text-gray-500 mt-1">{proxies.length} proxy(s) vendu(s)</p></div><button onClick={exportCsv} className="h-11 px-4 rounded-xl bg-primary text-gray-950 font-black text-sm flex items-center gap-2"><Download size={16} /> Export CSV</button></div>
    <div className="bg-white dark:bg-slate-900 border border-gray-100 dark:border-slate-800 rounded-[2rem] overflow-hidden"><div className="p-5 border-b border-gray-100 dark:border-slate-800"><div className="max-w-md h-11 px-4 rounded-xl bg-gray-50 dark:bg-slate-800 flex items-center gap-2"><Search size={16} className="text-gray-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="IP, client, pays ou commande…" className="w-full bg-transparent outline-none text-sm" /></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase tracking-wider text-gray-400 bg-gray-50 dark:bg-slate-800/50"><tr><th className="p-4">IP / Port</th><th className="p-4">Client</th><th className="p-4">Pays</th><th className="p-4">État</th><th className="p-4">Expiration</th><th className="p-4">Vente</th><th className="p-4">Marge</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-slate-800">{visible.map(p => <tr key={`${p.orderId}-${p.id}`}><td className="p-4 font-mono font-bold">{p.host}:{p.port}</td><td className="p-4"><div className="font-bold">{p.buyerEmail || '—'}</div><div className="text-[10px] text-gray-400 font-mono">{String(p.orderId).slice(0, 8)}</div></td><td className="p-4">{p.country}</td><td className="p-4 font-bold capitalize">{proxyStatus(p)}</td><td className="p-4">{p.expire_time ? new Date(Number(p.expire_time) * 1000).toLocaleDateString('fr-FR') : '—'}</td><td className="p-4 font-bold">${p.salePrice.toFixed(2)}</td><td className="p-4 font-bold text-primary">${(p.salePrice - p.supplierCost).toFixed(2)}</td></tr>)}</tbody></table>{!visible.length && <div className="py-20 text-center text-sm text-gray-400">Aucun proxy vendu pour le moment.</div>}</div></div>
  </div>;
}
